config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'our-work' => 'our_work#index'
  get 'case-studies' => 'pages#case_studies'
  get 'case-studies/mike-the-barber' => 'pages#mike_the_barber'
  get 'case-studies/4x4_day' => 'pages#4x4_day'
  get 'studio' => 'pages#studio'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/our_work_controller.rb
class OurWorkController < ApplicationController
  def index
    @src = params[:src]
    render :show if @src
  end

  def show
    @src = params[:src]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/our_work_helper.rb
module OurWorkHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.haml
%footer.relative
  .row.expanded
    .column.center-text
      %h2.header Contact
      %p.contacts
        72 Auburn Ave.
        %br
        Pontiac, MI 48342
        %br
        = link_to '248.787.0728', 'tel:2487870728'
        %br
        = link_to 'howdy@tibbsinc.com', 'mailto:howdy@tibbsinc.com', target: '_blank'
      = link_to 'https://www.instagram.com/tibbs_inc/', target: '_blank' do
        %i.fa.fa-instagram
      = link_to 'https://www.facebook.com/tibbsincorporated', target: '_blank' do
        %i.fa.fa-facebook-square

app/views/layouts/_header.html.haml
%header
  = link_to root_path, class: 'logo black-logo hide' do
    =image_tag 'layouts/logo_black.png'
  = link_to root_path, class: 'logo white-logo' do
    =image_tag 'layouts/logo_white.png'
  %div.hamburger.hamburger--squeeze{type: 'button'}
    %div.hamburger-box
      %div.hamburger-inner
.menu
  %ul
    %li
      = link_to 'Company', root_path, class: 'nav-link uppercase'
    %li
      = link_to 'Case Studies', case_studies_path, class: 'nav-link uppercase'
    %li
      = link_to 'Our Work', our_work_path, class: 'nav-link uppercase'
    %li
      = link_to 'Studio', studio_path, class: 'nav-link uppercase'
    %li
      = link_to 'Bio', '#', class: 'nav-link uppercase coming-soon'
    %li
      = link_to 'Contact', 'mailto:howdy@tibbsinc.com', class: 'nav-link uppercase', target: '_blank'

:javascript
  var prevText;

  $('.coming-soon').mouseenter(function() {
    prevText = $(this).text();
    $(this).text('COMING SOON');
  });

  $('.coming-soon').mouseout(function() {
    $(this).text(prevText);
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= tag :meta, name: :psj, action: action_name %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/our_work/_video.html.haml
.video-wrapper
  = video_tag "https://tibbs-videos.s3.us-east-2.amazonaws.com/videos/#{@src}" || '#', controls: true, class: 'video', autoplay: true

app/views/our_work/index.html.haml
.place-holder

%section.header-section
  .row
    .column
      %h1.header Our Work
%section.video-player
  .row
    .column.test
      .video-wrapper
%section.posters
  .row
    .column.videos
      .poster.relative.gymboree(value='rocket')
        = image_tag 'pages/our_work/rocket.jpg'
        .hover-info
          .wrapper.center-text
            %h2 My Chevy is a Rocket
      .poster.relative.gymboree(value='gymboree')
        = image_tag 'pages/our_work/gymboree.jpg'
        .hover-info
          .wrapper.center-text
            %h2 Gymboree
      .poster.relative.biolite(value='biolite')
        = image_tag 'pages/our_work/biolite.jpg'
        .hover-info
          .wrapper.center-text
            %h2 Biolite
      .poster.relative.bcbsm_2(value='bcbsm_2')
        = image_tag 'pages/our_work/bcbsm_2.jpg'
        .hover-info
          .wrapper.center-text
            %h2 BCBSM | Dr. Daniels
      .poster.relative.bcbsm(value='bcbsm')
        = image_tag 'pages/our_work/bcbsm.jpg'
        .hover-info
          .wrapper.center-text
            %h2 BCBSM | City on a Hill
      .poster.relative.jeep-day(value='jeep_day')
        = image_tag 'pages/our_work/jeep_day.jpg'
        .hover-info
          .wrapper.center-text
            %h2 4X4 Day | JEEP
      .poster.relative.jeep-unmelting(value='jeep_unmelting')
        = image_tag 'pages/our_work/unmelting.jpg'
        .hover-info
          .wrapper.center-text
            %h2 The Unmelting | JEEP
      .poster.relative.mike-the-barber(value='mike_the_barber')
        = image_tag 'pages/our_work/mike.jpg'
        .hover-info
          .wrapper.center-text
            %h2 Mike The Barber
      .poster.relative.submaster(value='submaster')
        = image_tag 'pages/our_work/submaster.jpg'
        .hover-info
          .wrapper.center-text
            %h2 Submaster | Ford
      .poster.relative.trackhawk(value='trackhawk')
        = image_tag 'pages/our_work/trackhawk.jpg'
        .hover-info
          .wrapper.center-text
            %h2 Trackhawk | JEEP

app/views/our_work/show.js.erb
$('.video-wrapper').remove();
$('.test').append("<%= j(render('video'))%>");

app/views/pages/4x4_day.html.haml
.place-holder

#case-study.center-text.jeep-day-case-study
  %section.even-padding.one.even-padding
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/jeep/jeep_8.jpg'
      .column.large-6.small-12
        %h2.header 4X4 DAY | JEEP
        %p.paragraph So JEEP Brand calls us and says, “Hey, we need help breaking a few hundred thousand employees out of the workspace this 4X4 Day (April 4th), can you help us?”
        %p.paragraph Because here at Tibbs Inc. we’re all about sticking it to the man, we unequivocally accepted the mission – Let’s Go!
  %section.even-padding.two
    .row.align-middle
      .column.large-6.small-12.large-order-2
        = image_tag 'pages/jeep/jeep_7.jpg'
      .column.large-6.small-12.large-order-1
        %p.paragraph “We were shooting a spring spot at the beginning of March in the Midwest. It was important to keep the off-roading footage as indefinite as we could. We’re hoping you the viewer didn’t notice the chunks of ice floating in the mud puddles we ran the vehicles through.”
  %section.even-padding.three
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/jeep/jeep_2.jpg'
      .column.large-6.small-12
        %h2.header The Task
        %p.paragraph Jeep brand asked us to film 4 scripts that would be used to break Jeep owners out of the office on 4X4 Day. These spots needed to be snappy and smart. Our main gag was to incorporate a lifelike mannequin in place of our principal employee. Once we broke her out, we needed to get the Wrangler from a typical office location to a dramatic off-road space to help sell the escape.
  %section.even-padding.four
    .row.align-middle
      .column.large-6.small-12.large-order-2
        = image_tag 'pages/jeep/jeep_1.jpg'
      .column.large-6.small-12.large-order-1
        %h2.header Pre-Production
        %p.paragraph We wanted to contrast the doldrums of cubicle life with the excitement of mud bogging in a Wrangler. It was a pleasant surprise to find most offices have gotten away from the paper-pushing cubicles we’ve come to despise. We needed to find a place that was cool enough for our Jeep owner to be working, yet, dated enough to want to escape from. Tracking down the perfect office proved to be the real undertaking.
        %p.paragraph “We wanted tall grey cubicles, big printers, and a halogen drop-ceiling.”
  %section.even-padding.five
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/jeep/jeep_3.jpg'
      .column.large-6.small-12
        %h2.header Production
        %p.paragraph We certainly felt the pressures of our schedule, we had a day to dress an office and break two employees out 4 different ways. We then needed to move our crew over 100 miles West to an old gravel mine to shoot the off-roading footage.
        %p.paragraph **Fun fact, the gravel out of that mine was used to lay a foundation on across some of Michigan’s largest highways.
  %section.even-padding.six
    .row.align-middle
      .column.large-6.small-12.large-order-2
        = image_tag 'pages/jeep/jeep_4.jpg'
      .column.large-6.small-12.large-order-1
        %h2.header Escape Routes
        %p.paragraph We decided that the use of graphic splits in our story would help keep the pace of the story up as well as juxtapose the fun our hero employee is having out on the trails while her counterpart is stuck in the office. Each escape route has its unique plan of attack, but all of them end with seamless success.
  %section.even-padding.seven
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/jeep/jeep_6.jpg'
      .column.large-6.small-12
        %h2.header Post-Production
        %p.paragraph Like most social pieces, it was important to create a high-impact narrative in a short amount of time. We wanted to tell two stories at once – the employee who got away, contrasted with the employee who was stuck in the office eating half of a sandwich. We implemented graphic lines that cut through the center, both vertically and horizontally throughout the piece that kept the pace high but covered off on all of the details we wanted the viewer to see.
  %section.even-padding.eight.video
    .row
      .column
        = video_tag 'https://tibbs-videos.s3.us-east-2.amazonaws.com/videos/jeep_day.mp4', autoplay: false, loop: false, controls: true, muted: false

app/views/pages/case_studies.html.haml
.place-holder

#case-studies
  %section.header-section
    .row
      .column
        %h1.header Case Studies
  %section.gallery
    .row.jeep-day.center-text
      .column.case-study-badge.small-12
        .badge-copy
          %h2.header.uppercase 4x4 Day | Jeep
          %h4.header Breaking JEEP owners out of the office one at a time.
          = link_to 'Case Study', case_studies_4x4_day_path, class: 'uppercase btn btn-black'
    .row.mike.center-text
      .column.case-study-badge.small-12
        .badge-copy
          %h2.header.uppercase Mike The Barber
          %h4.header A barber on a mission to give the perfect haircut
          = link_to 'Case Study', case_studies_mike_the_barber_path, class: 'uppercase btn btn-black'

app/views/pages/home.html.haml
#home
  %section.first
    .video
      = video_tag 'https://tibbs-videos.s3.us-east-2.amazonaws.com/videos/reel.mp4', autoplay: true, loop: true, controls: false, muted: true, playsinline: true
  %section.second.center-text.relative
    .row.center-ver-hrz
      .column
        %h2.header.uppercase Culture
        %p.copy
          We are a nimble yet powerful team of directors, producers, cinematographers, and designers with the ability to scale to any project, large or small. We all share a common credo; story first. Whether we find those stories, or they find us, we sink our teeth in and bring them to life.
          %br
          %br
          The goal is to engage. The challenge is to exceed expectations.
  .case-study-badges.relative
    .row.expanded
      .column.small-12.large-3.case-study-badge.jeep
        .badge-copy
          %h2.header.uppercase 4x4 Day | Jeep
          = link_to 'Case Study', case_studies_4x4_day_path, class: 'uppercase btn btn-black'
      .column.small-12.large-3.case-study-badge.biolite
        .badge-copy
          %h2.header.uppercase Biolite
          = link_to 'Our Work', our_work_path, class: 'uppercase btn btn-black'
      .column.small-12.large-6.case-study-badge.rocket
        .badge-copy
          %h2.header.uppercase My Chevy is a Rocket
          = link_to 'Our Work', our_work_path, class: 'uppercase btn btn-black'
      .column.small-12.large-6.studio-pic
        = image_tag 'studio/studio1.jpg'
      .column.small-12.large-6.studio-pic
        = image_tag 'studio/studio16.jpg'
  .row.expanded.collapse
    .column
      .quotes.slider.no-margin
        .slide
          .text-container
            %p.copy.quote
              “When you hand good people possibility, they do great things.”
              %br
              %br
              %span.author - Bizz Stone
        .slide
          .text-container
            %p.copy.quote
              “No one ever made a difference by being like everyone else.”
              %br
              %br
              %span.author - P T Barnum
        .slide
          .text-container
            %p.copy.quote
              “Art is not what you see but what you make others see.”
              %br
              %br
              %span.author - Degas

app/views/pages/mike_the_barber.html.haml
.place-holder

#case-study.center-text.mike-case-study
  %section.even-padding.one
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/mike/mike_1.jpg'
      .column.large-6.small-12
        %h2.header A Chance Encounter
        %p.paragraph.margin-top-bottom “My wife and I had a wedding to attend in June 2016. I remember having a pretty hectic week at work and was unable to get a haircut before the event. We were driving past this little one-room barbershop names Mike’s. I stopped in for a quick lineup and ended up befriending one of the kindest and quirkiest humans I had ever met.” – Ryan Wiese, Director
  %section.even-padding.two
    .row.align-middle
      .column.large-6.small-12.large-order-2
        = image_tag 'pages/mike/mike_6.jpg'
      .column.large-6.small-12.large-order-1
        %h2.header Finding the Story
        %p.paragraph.margin-top-bottom His barbershop is a blast from another time. It looked as though it had been decorated some 40 years ago and hadn’t been touched since. The first thing you notice when you walk into the shop is the abundance of Ohio State University memorabilia. Mike was fully aware that he owned a barbershop in the heart of Wolverine country, yet he hung the pro-Buckeye gear to get his customers, “hot under the collar”. He said, “for better or worse, they’re going to remember me.” He told this and other incredible stories which left me knowing his story needed to be brought to life.
  %section.even-padding.four.western
    .row
      .column.small-6
        = image_tag 'pages/mike/mike_5.jpg'
      .column.small-6
        = image_tag 'pages/mike/mike_3.jpg'
      .column.small-12
        %p.paragraph.margin-top-bottom Mike always has Western movies playing in the barbershop. Our DP Jerome recalled a very memorable scene in a John Wayne movie. We began explaining the scene him. Mike knew exactly the movie, Hondo, starring John Wayne, and had a copy on VHS for us to use. We ended up using that copy in the piece.
  %section.even-padding.three.no-copy
    .row.align-middle
      .column
        = image_tag 'pages/mike/mike_4.jpg', class: 'width-100'
  %section.even-padding.five
    .row.align-middle
      .column.large-6.small-12
        = image_tag 'pages/mike/mike_2.jpg'
      .column.large-6.small-12
        %h2.header The Perfect Song
        %p.paragraph.margin-top-bottom We ended up using a song by The Peddlers, On a Clear Day You Can See Forever. It was the first song that came to mind after the day we spent shooting with Mike and never changed. When we cut the initial edit the shot in the piece that follows our customer (Dan John Miller) from his boots up the chair to his hair just happened to land on the drum fill into the organ solo. After we saw that we cut the rest of the video around that specific shot and part in the song.
  %section.even-padding.even-padding.six.no-copy
  %section.even-padding.even-padding.seven
    .row.align-middle
      .column.large-6.small-12.large-order-2
        = image_tag 'pages/mike/mike_7.jpg'
      .column.large-6.small-12.large-order-1
        %h2.header Story Development
        %p.paragraph.margin-top-bottom The piece was created to detail a day in the life of an incredible man, who has spent most of his days cutting hair in a one-roomed barbershop. While we were filming, a 55-year-old man came in and recounted getting his first haircut from Mike right before his senior prom. It ended up taking months of visits, conversations, haircuts, and pre-production before we knew in what light we planned to tell his story.
  %section.even-padding.even-padding.eight.video
    .row
      .column
        = video_tag 'https://tibbs-videos.s3.us-east-2.amazonaws.com/videos/mike_the_barber.mp4', autoplay: false, loop: false, controls: true, muted: false

app/views/pages/our_work.html.haml
%section.video-player
  .row
    .column
      .video-wrapper
        = video_tag 'jeep_day.mp4', controls: true, class: 'video'
%section.posters
  .row
    .column.videos
      .poster(value='jeep_day')
        = image_tag 'pages/our_work/placeholder.png'
      .poster(value='jeep_unmelting')
        = image_tag 'pages/our_work/placeholder.png'
      .poster(value='mike_the_barber')
        = image_tag 'pages/our_work/placeholder.png'
      .poster(value='submaster')
        = image_tag 'pages/our_work/placeholder.png'
      .poster(value='trackhawk')
        = image_tag 'pages/our_work/placeholder.png'

app/views/pages/studio.html.haml
.place-holder

#studio
  %section.header-section
    .row
      .column
        %h1.header Studio
        %p The newly renovated 1912 Duffey building offers two full-service edit bays, as well as complete client service provisions
  %section.gallary
    .row
      .column.small-10.small-offset-1
        .studio-slider
          .slide
            = image_tag 'studio/studio1.jpg'
          .slide
            = image_tag 'studio/studio2.jpg'
          .slide
            = image_tag 'studio/studio3.jpg'
          .slide
            = image_tag 'studio/studio4.jpg'
          -# .slide
          -#   = image_tag 'studio/studio5.jpg'
          .slide
            = image_tag 'studio/studio6.jpg'
          .slide
            = image_tag 'studio/studio7.jpg'
          .slide
            = image_tag 'studio/studio8.jpg'
          .slide
            = image_tag 'studio/studio9.jpg'
          .slide
            = image_tag 'studio/studio10.jpg'
          .slide
            = image_tag 'studio/studio11.jpg'
          .slide
            = image_tag 'studio/studio12.jpg'
          .slide
            = image_tag 'studio/studio13.jpg'
          .slide
            = image_tag 'studio/studio14.jpg'
          .slide
            = image_tag 'studio/studio15.jpg'
          .slide
            = image_tag 'studio/studio16.jpg'
          .slide
            = image_tag 'studio/studio17.jpg'
  .row
    .column.center-text
      %p Photos by #{link_to 'Noah Elliot Morrison','https://noahmo.com/', target: '_blank'}

:javascript
  $(document).ready(function() {
    $('.studio-slider').slick({
      infinite: true,
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      buttons: true,
      autoplay: true,
      autoplaySpeed: 3000
    });
  });